# Practica 2

#Ejercicio 4

In [6]:
import numpy as np

dimensiones = []
print("Ingrese las dimensiones de la matriz")
dimensiones.append(int(input("x: ")))
dimensiones.append(int(input("y: ")))

rango = []
print("Ingrese el rango de valores")
rango.append(int(input("min: ")))
rango.append(int(input("max: ")))

def crearMatriz(dimensiones,rango):
    return (rango[1]-rango[0]) *np.random.rand(dimensiones[0],dimensiones[1]) + rango[0]

a = crearMatriz(dimensiones,rango) 
b = crearMatriz(dimensiones,rango) 
print('\nPrimera matriz\n%s\n' % a)
print('Segunda matriz\n%s\n' % b)
print('a @ b (Multiplicacion de matrices)\n%s\n' % (a @ b))
print('a * b (Multiplicacion Hadamard)\n%s\n' % (a * b))


Ingrese las dimensiones de la matriz
x: 5
y: 5
Ingrese el rango de valores
min: 1
max: 10

Primera matriz
[[9.99925486 8.34925008 6.27193415 1.22685526 1.60859039]
 [2.80767294 9.10966911 3.46900168 8.41718463 4.69395973]
 [9.98689394 9.0426119  3.21224657 1.30579644 1.2808199 ]
 [8.48777214 9.35477169 8.63045035 4.63019892 3.33674232]
 [8.62925944 1.0945112  1.05930705 2.58028178 9.53403031]]

Segunda matriz
[[7.08343293 3.36829737 7.82847648 9.27336223 8.9577116 ]
 [3.3220958  3.96021787 4.00736078 1.48893096 2.78064982]
 [3.48833444 6.00539327 1.02308282 2.76168544 3.49863043]
 [2.37601322 9.30082124 3.90634068 4.7472955  3.96544121]
 [2.55470313 1.43900211 9.13699042 3.77962196 4.23871952]]

a @ b (Multiplicacion de matrices)
[[127.46915891 118.13627079 137.64428651 134.38338658 146.41334758]
 [ 94.24321    151.40741861 137.80366413 106.88078401 115.89210862]
 [118.36201095 102.72842754 134.50929182 125.98714105 136.44961175]
 [140.8317095  165.33175469 161.33885227 151.06593094 16